// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

public interface BeginArgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.BeginArg)
    com.google.protobuf.MessageOrBuilder {
}
