// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Empty)
    com.google.protobuf.MessageOrBuilder {
}
