// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

/**
 * Protobuf enum {@code pb.ErrorType}
 */
public enum ErrorType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TxnError = 0;</code>
   */
  TxnError(0),
  /**
   * <code>KvError = 1;</code>
   */
  KvError(1),
  /**
   * <code>OtherError = 2;</code>
   */
  OtherError(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TxnError = 0;</code>
   */
  public static final int TxnError_VALUE = 0;
  /**
   * <code>KvError = 1;</code>
   */
  public static final int KvError_VALUE = 1;
  /**
   * <code>OtherError = 2;</code>
   */
  public static final int OtherError_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErrorType valueOf(int value) {
    return forNumber(value);
  }

  public static ErrorType forNumber(int value) {
    switch (value) {
      case 0: return TxnError;
      case 1: return KvError;
      case 2: return OtherError;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErrorType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErrorType>() {
          public ErrorType findValueByNumber(int number) {
            return ErrorType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return kvClient.pb.TxnPB.getDescriptor().getEnumTypes().get(1);
  }

  private static final ErrorType[] VALUES = values();

  public static ErrorType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErrorType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pb.ErrorType)
}

