// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

public interface GetArgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.GetArg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 txnid = 1;</code>
   */
  long getTxnid();

  /**
   * <code>.pb.Key key = 2;</code>
   */
  boolean hasKey();
  /**
   * <code>.pb.Key key = 2;</code>
   */
  kvClient.pb.Key getKey();
  /**
   * <code>.pb.Key key = 2;</code>
   */
  kvClient.pb.KeyOrBuilder getKeyOrBuilder();
}
