// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

public interface InsertArgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.InsertArg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 txnid = 1;</code>
   */
  long getTxnid();

  /**
   * <code>.pb.KeyValue kv = 2;</code>
   */
  boolean hasKv();
  /**
   * <code>.pb.KeyValue kv = 2;</code>
   */
  kvClient.pb.KeyValue getKv();
  /**
   * <code>.pb.KeyValue kv = 2;</code>
   */
  kvClient.pb.KeyValueOrBuilder getKvOrBuilder();
}
