// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

/**
 * Protobuf type {@code pb.InsertArg}
 */
public  final class InsertArg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.InsertArg)
    InsertArgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InsertArg.newBuilder() to construct.
  private InsertArg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InsertArg() {
    txnid_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InsertArg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            txnid_ = input.readInt64();
            break;
          }
          case 18: {
            kvClient.pb.KeyValue.Builder subBuilder = null;
            if (kv_ != null) {
              subBuilder = kv_.toBuilder();
            }
            kv_ = input.readMessage(kvClient.pb.KeyValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kv_);
              kv_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kvClient.pb.TxnPB.internal_static_pb_InsertArg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kvClient.pb.TxnPB.internal_static_pb_InsertArg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kvClient.pb.InsertArg.class, kvClient.pb.InsertArg.Builder.class);
  }

  public static final int TXNID_FIELD_NUMBER = 1;
  private long txnid_;
  /**
   * <code>int64 txnid = 1;</code>
   */
  public long getTxnid() {
    return txnid_;
  }

  public static final int KV_FIELD_NUMBER = 2;
  private kvClient.pb.KeyValue kv_;
  /**
   * <code>.pb.KeyValue kv = 2;</code>
   */
  public boolean hasKv() {
    return kv_ != null;
  }
  /**
   * <code>.pb.KeyValue kv = 2;</code>
   */
  public kvClient.pb.KeyValue getKv() {
    return kv_ == null ? kvClient.pb.KeyValue.getDefaultInstance() : kv_;
  }
  /**
   * <code>.pb.KeyValue kv = 2;</code>
   */
  public kvClient.pb.KeyValueOrBuilder getKvOrBuilder() {
    return getKv();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (txnid_ != 0L) {
      output.writeInt64(1, txnid_);
    }
    if (kv_ != null) {
      output.writeMessage(2, getKv());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (txnid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, txnid_);
    }
    if (kv_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getKv());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kvClient.pb.InsertArg)) {
      return super.equals(obj);
    }
    kvClient.pb.InsertArg other = (kvClient.pb.InsertArg) obj;

    boolean result = true;
    result = result && (getTxnid()
        == other.getTxnid());
    result = result && (hasKv() == other.hasKv());
    if (hasKv()) {
      result = result && getKv()
          .equals(other.getKv());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TXNID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTxnid());
    if (hasKv()) {
      hash = (37 * hash) + KV_FIELD_NUMBER;
      hash = (53 * hash) + getKv().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kvClient.pb.InsertArg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kvClient.pb.InsertArg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kvClient.pb.InsertArg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kvClient.pb.InsertArg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kvClient.pb.InsertArg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kvClient.pb.InsertArg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kvClient.pb.InsertArg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kvClient.pb.InsertArg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kvClient.pb.InsertArg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kvClient.pb.InsertArg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kvClient.pb.InsertArg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kvClient.pb.InsertArg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kvClient.pb.InsertArg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.InsertArg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.InsertArg)
      kvClient.pb.InsertArgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kvClient.pb.TxnPB.internal_static_pb_InsertArg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kvClient.pb.TxnPB.internal_static_pb_InsertArg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kvClient.pb.InsertArg.class, kvClient.pb.InsertArg.Builder.class);
    }

    // Construct using pb.InsertArg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      txnid_ = 0L;

      if (kvBuilder_ == null) {
        kv_ = null;
      } else {
        kv_ = null;
        kvBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kvClient.pb.TxnPB.internal_static_pb_InsertArg_descriptor;
    }

    public kvClient.pb.InsertArg getDefaultInstanceForType() {
      return kvClient.pb.InsertArg.getDefaultInstance();
    }

    public kvClient.pb.InsertArg build() {
      kvClient.pb.InsertArg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kvClient.pb.InsertArg buildPartial() {
      kvClient.pb.InsertArg result = new kvClient.pb.InsertArg(this);
      result.txnid_ = txnid_;
      if (kvBuilder_ == null) {
        result.kv_ = kv_;
      } else {
        result.kv_ = kvBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kvClient.pb.InsertArg) {
        return mergeFrom((kvClient.pb.InsertArg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kvClient.pb.InsertArg other) {
      if (other == kvClient.pb.InsertArg.getDefaultInstance()) return this;
      if (other.getTxnid() != 0L) {
        setTxnid(other.getTxnid());
      }
      if (other.hasKv()) {
        mergeKv(other.getKv());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kvClient.pb.InsertArg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kvClient.pb.InsertArg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long txnid_ ;
    /**
     * <code>int64 txnid = 1;</code>
     */
    public long getTxnid() {
      return txnid_;
    }
    /**
     * <code>int64 txnid = 1;</code>
     */
    public Builder setTxnid(long value) {
      
      txnid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 txnid = 1;</code>
     */
    public Builder clearTxnid() {
      
      txnid_ = 0L;
      onChanged();
      return this;
    }

    private kvClient.pb.KeyValue kv_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        kvClient.pb.KeyValue, kvClient.pb.KeyValue.Builder, kvClient.pb.KeyValueOrBuilder> kvBuilder_;
    /**
     * <code>.pb.KeyValue kv = 2;</code>
     */
    public boolean hasKv() {
      return kvBuilder_ != null || kv_ != null;
    }
    /**
     * <code>.pb.KeyValue kv = 2;</code>
     */
    public kvClient.pb.KeyValue getKv() {
      if (kvBuilder_ == null) {
        return kv_ == null ? kvClient.pb.KeyValue.getDefaultInstance() : kv_;
      } else {
        return kvBuilder_.getMessage();
      }
    }
    /**
     * <code>.pb.KeyValue kv = 2;</code>
     */
    public Builder setKv(kvClient.pb.KeyValue value) {
      if (kvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kv_ = value;
        onChanged();
      } else {
        kvBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pb.KeyValue kv = 2;</code>
     */
    public Builder setKv(
        kvClient.pb.KeyValue.Builder builderForValue) {
      if (kvBuilder_ == null) {
        kv_ = builderForValue.build();
        onChanged();
      } else {
        kvBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pb.KeyValue kv = 2;</code>
     */
    public Builder mergeKv(kvClient.pb.KeyValue value) {
      if (kvBuilder_ == null) {
        if (kv_ != null) {
          kv_ =
            kvClient.pb.KeyValue.newBuilder(kv_).mergeFrom(value).buildPartial();
        } else {
          kv_ = value;
        }
        onChanged();
      } else {
        kvBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pb.KeyValue kv = 2;</code>
     */
    public Builder clearKv() {
      if (kvBuilder_ == null) {
        kv_ = null;
        onChanged();
      } else {
        kv_ = null;
        kvBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pb.KeyValue kv = 2;</code>
     */
    public kvClient.pb.KeyValue.Builder getKvBuilder() {
      
      onChanged();
      return getKvFieldBuilder().getBuilder();
    }
    /**
     * <code>.pb.KeyValue kv = 2;</code>
     */
    public kvClient.pb.KeyValueOrBuilder getKvOrBuilder() {
      if (kvBuilder_ != null) {
        return kvBuilder_.getMessageOrBuilder();
      } else {
        return kv_ == null ?
            kvClient.pb.KeyValue.getDefaultInstance() : kv_;
      }
    }
    /**
     * <code>.pb.KeyValue kv = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        kvClient.pb.KeyValue, kvClient.pb.KeyValue.Builder, kvClient.pb.KeyValueOrBuilder> 
        getKvFieldBuilder() {
      if (kvBuilder_ == null) {
        kvBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            kvClient.pb.KeyValue, kvClient.pb.KeyValue.Builder, kvClient.pb.KeyValueOrBuilder>(
                getKv(),
                getParentForChildren(),
                isClean());
        kv_ = null;
      }
      return kvBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.InsertArg)
  }

  // @@protoc_insertion_point(class_scope:pb.InsertArg)
  private static final kvClient.pb.InsertArg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kvClient.pb.InsertArg();
  }

  public static kvClient.pb.InsertArg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InsertArg>
      PARSER = new com.google.protobuf.AbstractParser<InsertArg>() {
    public InsertArg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InsertArg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InsertArg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InsertArg> getParserForType() {
    return PARSER;
  }

  public kvClient.pb.InsertArg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

