// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

/**
 * Protobuf enum {@code pb.Op}
 */
public enum Op
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Begin = 0;</code>
   */
  Begin(0),
  /**
   * <code>Commit = 1;</code>
   */
  Commit(1),
  /**
   * <code>Abort = 2;</code>
   */
  Abort(2),
  /**
   * <code>Rollback = 3;</code>
   */
  Rollback(3),
  /**
   * <code>IsAlive = 4;</code>
   */
  IsAlive(4),
  /**
   * <code>Insert = 5;</code>
   */
  Insert(5),
  /**
   * <code>Delete = 6;</code>
   */
  Delete(6),
  /**
   * <code>Get = 7;</code>
   */
  Get(7),
  /**
   * <code>Set = 8;</code>
   */
  Set(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Begin = 0;</code>
   */
  public static final int Begin_VALUE = 0;
  /**
   * <code>Commit = 1;</code>
   */
  public static final int Commit_VALUE = 1;
  /**
   * <code>Abort = 2;</code>
   */
  public static final int Abort_VALUE = 2;
  /**
   * <code>Rollback = 3;</code>
   */
  public static final int Rollback_VALUE = 3;
  /**
   * <code>IsAlive = 4;</code>
   */
  public static final int IsAlive_VALUE = 4;
  /**
   * <code>Insert = 5;</code>
   */
  public static final int Insert_VALUE = 5;
  /**
   * <code>Delete = 6;</code>
   */
  public static final int Delete_VALUE = 6;
  /**
   * <code>Get = 7;</code>
   */
  public static final int Get_VALUE = 7;
  /**
   * <code>Set = 8;</code>
   */
  public static final int Set_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Op valueOf(int value) {
    return forNumber(value);
  }

  public static Op forNumber(int value) {
    switch (value) {
      case 0: return Begin;
      case 1: return Commit;
      case 2: return Abort;
      case 3: return Rollback;
      case 4: return IsAlive;
      case 5: return Insert;
      case 6: return Delete;
      case 7: return Get;
      case 8: return Set;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Op>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Op> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Op>() {
          public Op findValueByNumber(int number) {
            return Op.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return kvClient.pb.TxnPB.getDescriptor().getEnumTypes().get(0);
  }

  private static final Op[] VALUES = values();

  public static Op valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Op(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pb.Op)
}

