// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 txnid = 1;</code>
   */
  long getTxnid();

  /**
   * <code>bool res = 2;</code>
   */
  boolean getRes();

  /**
   * <code>.pb.ServiceError e = 3;</code>
   */
  boolean hasE();
  /**
   * <code>.pb.ServiceError e = 3;</code>
   */
  kvClient.pb.ServiceError getE();
  /**
   * <code>.pb.ServiceError e = 3;</code>
   */
  kvClient.pb.ServiceErrorOrBuilder getEOrBuilder();

  public kvClient.pb.Response.ResultCase getResultCase();
}
