// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

/**
 * Protobuf type {@code pb.Response}
 */
public  final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    txnid_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            txnid_ = input.readInt64();
            break;
          }
          case 16: {
            resultCase_ = 2;
            result_ = input.readBool();
            break;
          }
          case 26: {
            kvClient.pb.ServiceError.Builder subBuilder = null;
            if (resultCase_ == 3) {
              subBuilder = ((kvClient.pb.ServiceError) result_).toBuilder();
            }
            result_ =
                input.readMessage(kvClient.pb.ServiceError.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((kvClient.pb.ServiceError) result_);
              result_ = subBuilder.buildPartial();
            }
            resultCase_ = 3;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kvClient.pb.TxnPB.internal_static_pb_Response_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kvClient.pb.TxnPB.internal_static_pb_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kvClient.pb.Response.class, kvClient.pb.Response.Builder.class);
  }

  private int resultCase_ = 0;
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite {
    RES(2),
    E(3),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 2: return RES;
        case 3: return E;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int TXNID_FIELD_NUMBER = 1;
  private long txnid_;
  /**
   * <code>int64 txnid = 1;</code>
   */
  public long getTxnid() {
    return txnid_;
  }

  public static final int RES_FIELD_NUMBER = 2;
  /**
   * <code>bool res = 2;</code>
   */
  public boolean getRes() {
    if (resultCase_ == 2) {
      return (java.lang.Boolean) result_;
    }
    return false;
  }

  public static final int E_FIELD_NUMBER = 3;
  /**
   * <code>.pb.ServiceError e = 3;</code>
   */
  public boolean hasE() {
    return resultCase_ == 3;
  }
  /**
   * <code>.pb.ServiceError e = 3;</code>
   */
  public kvClient.pb.ServiceError getE() {
    if (resultCase_ == 3) {
       return (kvClient.pb.ServiceError) result_;
    }
    return kvClient.pb.ServiceError.getDefaultInstance();
  }
  /**
   * <code>.pb.ServiceError e = 3;</code>
   */
  public kvClient.pb.ServiceErrorOrBuilder getEOrBuilder() {
    if (resultCase_ == 3) {
       return (kvClient.pb.ServiceError) result_;
    }
    return kvClient.pb.ServiceError.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (txnid_ != 0L) {
      output.writeInt64(1, txnid_);
    }
    if (resultCase_ == 2) {
      output.writeBool(
          2, (boolean)((java.lang.Boolean) result_));
    }
    if (resultCase_ == 3) {
      output.writeMessage(3, (kvClient.pb.ServiceError) result_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (txnid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, txnid_);
    }
    if (resultCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            2, (boolean)((java.lang.Boolean) result_));
    }
    if (resultCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (kvClient.pb.ServiceError) result_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kvClient.pb.Response)) {
      return super.equals(obj);
    }
    kvClient.pb.Response other = (kvClient.pb.Response) obj;

    boolean result = true;
    result = result && (getTxnid()
        == other.getTxnid());
    result = result && getResultCase().equals(
        other.getResultCase());
    if (!result) return false;
    switch (resultCase_) {
      case 2:
        result = result && (getRes()
            == other.getRes());
        break;
      case 3:
        result = result && getE()
            .equals(other.getE());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TXNID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTxnid());
    switch (resultCase_) {
      case 2:
        hash = (37 * hash) + RES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRes());
        break;
      case 3:
        hash = (37 * hash) + E_FIELD_NUMBER;
        hash = (53 * hash) + getE().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kvClient.pb.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kvClient.pb.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kvClient.pb.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kvClient.pb.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kvClient.pb.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kvClient.pb.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kvClient.pb.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kvClient.pb.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kvClient.pb.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kvClient.pb.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kvClient.pb.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kvClient.pb.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kvClient.pb.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.Response)
      kvClient.pb.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kvClient.pb.TxnPB.internal_static_pb_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kvClient.pb.TxnPB.internal_static_pb_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kvClient.pb.Response.class, kvClient.pb.Response.Builder.class);
    }

    // Construct using pb.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      txnid_ = 0L;

      resultCase_ = 0;
      result_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kvClient.pb.TxnPB.internal_static_pb_Response_descriptor;
    }

    public kvClient.pb.Response getDefaultInstanceForType() {
      return kvClient.pb.Response.getDefaultInstance();
    }

    public kvClient.pb.Response build() {
      kvClient.pb.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kvClient.pb.Response buildPartial() {
      kvClient.pb.Response result = new kvClient.pb.Response(this);
      result.txnid_ = txnid_;
      if (resultCase_ == 2) {
        result.result_ = result_;
      }
      if (resultCase_ == 3) {
        if (eBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = eBuilder_.build();
        }
      }
      result.resultCase_ = resultCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kvClient.pb.Response) {
        return mergeFrom((kvClient.pb.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kvClient.pb.Response other) {
      if (other == kvClient.pb.Response.getDefaultInstance()) return this;
      if (other.getTxnid() != 0L) {
        setTxnid(other.getTxnid());
      }
      switch (other.getResultCase()) {
        case RES: {
          setRes(other.getRes());
          break;
        }
        case E: {
          mergeE(other.getE());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kvClient.pb.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kvClient.pb.Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }


    private long txnid_ ;
    /**
     * <code>int64 txnid = 1;</code>
     */
    public long getTxnid() {
      return txnid_;
    }
    /**
     * <code>int64 txnid = 1;</code>
     */
    public Builder setTxnid(long value) {
      
      txnid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 txnid = 1;</code>
     */
    public Builder clearTxnid() {
      
      txnid_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>bool res = 2;</code>
     */
    public boolean getRes() {
      if (resultCase_ == 2) {
        return (java.lang.Boolean) result_;
      }
      return false;
    }
    /**
     * <code>bool res = 2;</code>
     */
    public Builder setRes(boolean value) {
      resultCase_ = 2;
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool res = 2;</code>
     */
    public Builder clearRes() {
      if (resultCase_ == 2) {
        resultCase_ = 0;
        result_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        kvClient.pb.ServiceError, kvClient.pb.ServiceError.Builder, kvClient.pb.ServiceErrorOrBuilder> eBuilder_;
    /**
     * <code>.pb.ServiceError e = 3;</code>
     */
    public boolean hasE() {
      return resultCase_ == 3;
    }
    /**
     * <code>.pb.ServiceError e = 3;</code>
     */
    public kvClient.pb.ServiceError getE() {
      if (eBuilder_ == null) {
        if (resultCase_ == 3) {
          return (kvClient.pb.ServiceError) result_;
        }
        return kvClient.pb.ServiceError.getDefaultInstance();
      } else {
        if (resultCase_ == 3) {
          return eBuilder_.getMessage();
        }
        return kvClient.pb.ServiceError.getDefaultInstance();
      }
    }
    /**
     * <code>.pb.ServiceError e = 3;</code>
     */
    public Builder setE(kvClient.pb.ServiceError value) {
      if (eBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        eBuilder_.setMessage(value);
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <code>.pb.ServiceError e = 3;</code>
     */
    public Builder setE(
        kvClient.pb.ServiceError.Builder builderForValue) {
      if (eBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        eBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <code>.pb.ServiceError e = 3;</code>
     */
    public Builder mergeE(kvClient.pb.ServiceError value) {
      if (eBuilder_ == null) {
        if (resultCase_ == 3 &&
            result_ != kvClient.pb.ServiceError.getDefaultInstance()) {
          result_ = kvClient.pb.ServiceError.newBuilder((kvClient.pb.ServiceError) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 3) {
          eBuilder_.mergeFrom(value);
        }
        eBuilder_.setMessage(value);
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <code>.pb.ServiceError e = 3;</code>
     */
    public Builder clearE() {
      if (eBuilder_ == null) {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
        }
        eBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.pb.ServiceError e = 3;</code>
     */
    public kvClient.pb.ServiceError.Builder getEBuilder() {
      return getEFieldBuilder().getBuilder();
    }
    /**
     * <code>.pb.ServiceError e = 3;</code>
     */
    public kvClient.pb.ServiceErrorOrBuilder getEOrBuilder() {
      if ((resultCase_ == 3) && (eBuilder_ != null)) {
        return eBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 3) {
          return (kvClient.pb.ServiceError) result_;
        }
        return kvClient.pb.ServiceError.getDefaultInstance();
      }
    }
    /**
     * <code>.pb.ServiceError e = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        kvClient.pb.ServiceError, kvClient.pb.ServiceError.Builder, kvClient.pb.ServiceErrorOrBuilder> 
        getEFieldBuilder() {
      if (eBuilder_ == null) {
        if (!(resultCase_ == 3)) {
          result_ = kvClient.pb.ServiceError.getDefaultInstance();
        }
        eBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            kvClient.pb.ServiceError, kvClient.pb.ServiceError.Builder, kvClient.pb.ServiceErrorOrBuilder>(
                (kvClient.pb.ServiceError) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 3;
      onChanged();;
      return eBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.Response)
  }

  // @@protoc_insertion_point(class_scope:pb.Response)
  private static final kvClient.pb.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kvClient.pb.Response();
  }

  public static kvClient.pb.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  public kvClient.pb.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

