// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

public interface ServiceErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.ServiceError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.pb.ErrorType et = 2;</code>
   */
  int getEtValue();
  /**
   * <code>.pb.ErrorType et = 2;</code>
   */
  kvClient.pb.ErrorType getEt();
}
