// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: txn.proto

package kvClient.pb;

public final class TxnPB {
  private TxnPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Key_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_KeyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_BeginArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_BeginArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_CommitArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_CommitArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_AbortArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_AbortArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_RollbackArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_RollbackArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_InsertArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_InsertArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_DeleteArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_DeleteArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_GetArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_GetArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SetArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SetArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_IsAliveArg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_IsAliveArg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ServiceError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ServiceError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ResponseKv_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ResponseKv_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ttxn.proto\022\002pb\"\007\n\005Empty\"\022\n\003Key\022\013\n\003key\030\001" +
      " \001(\t\"\026\n\005Value\022\r\n\005value\030\001 \001(\t\"&\n\010KeyValue" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\n\n\010BeginArg" +
      "\"\032\n\tCommitArg\022\r\n\005txnid\030\001 \001(\003\"\031\n\010AbortArg" +
      "\022\r\n\005txnid\030\001 \001(\003\"\034\n\013RollbackArg\022\r\n\005txnid\030" +
      "\001 \001(\003\"4\n\tInsertArg\022\r\n\005txnid\030\001 \001(\003\022\030\n\002kv\030" +
      "\002 \001(\0132\014.pb.KeyValue\"0\n\tDeleteArg\022\r\n\005txni" +
      "d\030\001 \001(\003\022\024\n\003key\030\002 \001(\0132\007.pb.Key\"-\n\006GetArg\022" +
      "\r\n\005txnid\030\001 \001(\003\022\024\n\003key\030\002 \001(\0132\007.pb.Key\"1\n\006" +
      "SetArg\022\r\n\005txnid\030\001 \001(\003\022\030\n\002kv\030\002 \001(\0132\014.pb.K" +
      "eyValue\"\033\n\nIsAliveArg\022\r\n\005txnid\030\001 \001(\003\"6\n\014" +
      "ServiceError\022\013\n\003msg\030\001 \001(\t\022\031\n\002et\030\002 \001(\0162\r." +
      "pb.ErrorType\"v\n\nResponseKv\022\r\n\005txnid\030\001 \001(" +
      "\003\022\032\n\002kv\030\002 \001(\0132\014.pb.KeyValueH\000\022\024\n\001k\030\003 \001(\013" +
      "2\007.pb.KeyH\000\022\035\n\001e\030\004 \001(\0132\020.pb.ServiceError" +
      "H\000B\010\n\006result\"Q\n\010Response\022\r\n\005txnid\030\001 \001(\003\022" +
      "\r\n\003res\030\002 \001(\010H\000\022\035\n\001e\030\003 \001(\0132\020.pb.ServiceEr" +
      "rorH\000B\010\n\006result*k\n\002Op\022\t\n\005Begin\020\000\022\n\n\006Comm" +
      "it\020\001\022\t\n\005Abort\020\002\022\014\n\010Rollback\020\003\022\013\n\007IsAlive" +
      "\020\004\022\n\n\006Insert\020\005\022\n\n\006Delete\020\006\022\007\n\003Get\020\007\022\007\n\003S" +
      "et\020\010*6\n\tErrorType\022\014\n\010TxnError\020\000\022\013\n\007KvErr" +
      "or\020\001\022\016\n\nOtherError\020\0022\364\002\n\tKvService\022%\n\005Be" +
      "gin\022\014.pb.BeginArg\032\014.pb.Response\"\000\022\'\n\006Com" +
      "mit\022\r.pb.CommitArg\032\014.pb.Response\"\000\022%\n\005Ab" +
      "ort\022\014.pb.AbortArg\032\014.pb.Response\"\000\022+\n\010Rol" +
      "lback\022\017.pb.RollbackArg\032\014.pb.Response\"\000\022)" +
      "\n\007IsAlive\022\016.pb.IsAliveArg\032\014.pb.Response\"" +
      "\000\022\'\n\006Insert\022\r.pb.InsertArg\032\014.pb.Response" +
      "\"\000\022\'\n\006Delete\022\r.pb.DeleteArg\032\014.pb.Respons" +
      "e\"\000\022#\n\003Get\022\n.pb.GetArg\032\016.pb.ResponseKv\"\000" +
      "\022!\n\003Set\022\n.pb.SetArg\032\014.pb.Response\"\000B\r\n\002p" +
      "bB\005TxnPBP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_pb_Key_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Key_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_pb_Value_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Value_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_pb_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pb_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_KeyValue_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pb_BeginArg_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pb_BeginArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_BeginArg_descriptor,
        new java.lang.String[] { });
    internal_static_pb_CommitArg_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pb_CommitArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_CommitArg_descriptor,
        new java.lang.String[] { "Txnid", });
    internal_static_pb_AbortArg_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pb_AbortArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_AbortArg_descriptor,
        new java.lang.String[] { "Txnid", });
    internal_static_pb_RollbackArg_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_pb_RollbackArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_RollbackArg_descriptor,
        new java.lang.String[] { "Txnid", });
    internal_static_pb_InsertArg_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_pb_InsertArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_InsertArg_descriptor,
        new java.lang.String[] { "Txnid", "Kv", });
    internal_static_pb_DeleteArg_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_pb_DeleteArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_DeleteArg_descriptor,
        new java.lang.String[] { "Txnid", "Key", });
    internal_static_pb_GetArg_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_pb_GetArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_GetArg_descriptor,
        new java.lang.String[] { "Txnid", "Key", });
    internal_static_pb_SetArg_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_pb_SetArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SetArg_descriptor,
        new java.lang.String[] { "Txnid", "Kv", });
    internal_static_pb_IsAliveArg_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_pb_IsAliveArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_IsAliveArg_descriptor,
        new java.lang.String[] { "Txnid", });
    internal_static_pb_ServiceError_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_pb_ServiceError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ServiceError_descriptor,
        new java.lang.String[] { "Msg", "Et", });
    internal_static_pb_ResponseKv_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_pb_ResponseKv_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ResponseKv_descriptor,
        new java.lang.String[] { "Txnid", "Kv", "K", "E", "Result", });
    internal_static_pb_Response_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_pb_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Response_descriptor,
        new java.lang.String[] { "Txnid", "Res", "E", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
